### ISSUE TITLE
Monogame 3.3 support

### ISSUE THREAD

**Issue by aravol** [EmptyKeys/UI_Examples#1]
Unable to build the samples with MonoGame 3.3 installed. Appears the samples are still bound to MonoGame 3.2

**Comment by EmptyKeys** [comment]
Hi, only Linux, Win Desktop and WinStore examples were updated to MonoGame 3.3. The rest will be updated soon.

**Comment by aravol** [comment]
Will this include switching over the to the asset builder tool? I found no content in the projects themselves, but noted the Contentproj still in place

**Comment by EmptyKeys** [comment]
Most likely not. I use XNA Content Project for examples, but you can use whatever you want on your projects.

**Comment by aravol** [comment]
Seeing as those don't seem to be supported on higher versions of Visaul Studio, is there at least a chance we could see the assets from the samples come precompiled? Seems there's a lot lost on samples when we have to reconstruct their content by hand

**Comment by EmptyKeys** [comment]
XNA Content Project works without any problem in VS 2013, which is main platform for this library and examples. You can download it from http://mxa.codeplex.com/releases

**Comment by EmptyKeys** [comment]
I removed old Content project and replaced it with new one.
