### ISSUE TITLE
veldrid samples request

### ISSUE THREAD

**Issue by Shadow4walker** [EmptyKeys/UI_Examples#12]
thanks for this awesome library but can you make it work with [veldrid](https://github.com/mellinoe/veldrid) I've didn't know how to port it for veldrid from these examples! any hint on how to successfully port it

**Comment by EmptyKeys** [comment]
Hi,
Full sources of code, which you have to change is here

https://github.com/EmptyKeys/UI_Engines

There are two supported engines Monogame and Xenko. Pick one as inspiration and reimplement classes for veldrid.

**Comment by Shadow4walker** [comment]
i know about those samples but didn't know how to reimplement classes for veldrid! please consider port it if u got time
