### ISSUE TITLE
Xenko v3.1 Upgrade

### ISSUE THREAD

**Issue by PizzaConsole** [EmptyKeys/UI_Examples#14]
Xenko needs to be upgraded to v3.1.0.1

**Comment by EmptyKeys** [comment]
Hi,
You can go here https://github.com/EmptyKeys/UI_Engines , download it, build it with the new Xenko version.

**Comment by PizzaConsole** [comment]
The sample project doesn't work with Xenko 3.1
The EmptyKeys.UserInterface.Xenko project still references PackageReference Include="Xenko" Version="3.0.0.5"
