### ISSUE TITLE
Any examples of DataGrid usage?

### ISSUE THREAD

**Issue by WasabiFan** [EmptyKeys/UI_Examples#2]
I'm currently trying to use the `DataGrid` control and can't find any examples or documentation on its usage with this library.

When I declare a plain `DataGrid` and give it an `ItemsSource`, it works fine: it renders the data with column headers that are auto-chosen based on the property names. But when I set `AutoGenerateColumns` to `false` and then add template columns, the `AutoGenerateColumns` change shows up in the `.xaml.cs` file but the actual column definitions don't. So, are there any examples that you provide on how to do this? I think this would be a good addition to this "UI_Examples" repo.

**Comment by EmptyKeys** [comment]
Hi, ideally it should be the same like in WPF, but DataGrid does not support custom columns at this moment. I created it just for my internal tool and didn't need that feature yet. I will add that to my backlog http://emptykeys.com/Community/aft/12

**Comment by EmptyKeys** [comment]
Custom columns are implemented in next version (release Monday 1st June) , including simple example. Closing this.
