### ISSUE TITLE
Add a way to resize engines or renderers

### ISSUE THREAD

**Issue by ala53** [EmptyKeys/UI_Examples#3]
Hello,
I wasn't sure where to post this - EmptyKeys isn't open source - so I figured that the UI examples was close enough. 

Often times, resizing a window is necessary in a game for any number of reasons. However, I keep having to recreate the Engine instance to allow that to happen. Would it be possible to (a) expose the setters for NativeWidth and NativeHeight, (b) add a Resize() function to Engine, or (c) add a Resize() function to Renderer()?

By the way, are there any plans to open source the core of EmptyKeys?

**Comment by EmptyKeys** [comment]
Hi,
Resize method is on UIRoot instance ... so uiRoot.Resize(newWidth, newHeight)

I don't plan to open source main library for now, but thinking to open source engine specific ones so anyone can make support for another engine. UI Generator is open source and that's enough for anyone to extend library.

**Comment by ala53** [comment]
Hi,
Thanks for replying so quickly.
 If you only resize UIRoots, then what is the nativeResolution option for Renderers?

**Comment by EmptyKeys** [comment]
You can have different resolution and view port. This can happen in full screen mode (and in some cases with window mode). So in that case I need two sizes to be able to calculate mouse position properly. That's all. Be careful with resizing especially with window mode. You can get to the point, where mouse won't work. I don't know how to solve that issue at this moment.

**Comment by ala53** [comment]
Ok, so if I want a resizable window:

```
uiRoot.Resize(newWidth, newHeight)
var engine = new Engine(GraphicsDevice, newWidth, newHeight)
```

And that should keep mouse calculations correct. Do I have that right?

**Comment by EmptyKeys** [comment]
I use this

```
    private void Window_ClientSizeChanged(object sender, EventArgs e)
    {
        if (uiRoot != null)
        {
            if (graphics.PreferredBackBufferHeight != Window.ClientBounds.Height || graphics.PreferredBackBufferWidth != Window.ClientBounds.Width)
            {
                graphics.PreferredBackBufferWidth = Window.ClientBounds.Width;
                graphics.PreferredBackBufferHeight = Window.ClientBounds.Height;
                graphics.ApplyChanges();
            }

            Viewport viewport = GraphicsDevice.Viewport;
            uiRoot.Resize(viewport.Width, viewport.Height);
        }
    }
```

and Window.ClientSizeChanged += Window_ClientSizeChanged; in constructor of Game class.

**Comment by ala53** [comment]
But won't that cause the mouse position to be incorrect because `engine` now has the incorrect resolution?

**Comment by EmptyKeys** [comment]
That's OK for window mode. BTW there is a small issue with resizing Tab Control content at current version. Fix in the next release. :)
