### ISSUE TITLE
Paradox sample doesn't work

### ISSUE THREAD

**Issue by h-sao** [EmptyKeys/UI_Examples#4]
Hello,

I try to use EmptyKeys on Paradox.
// Paradox release 1.1.2-beta
But error occurred it.
![paradox](https://cloud.githubusercontent.com/assets/778582/7857470/871a5cd2-056b-11e5-8eea-14eb1c0e3317.png)
incorrect version???

**Comment by EmptyKeys** [comment]
Guys are too fast with updates :) let me recompile and quick test for 1.1.2b

**Comment by EmptyKeys** [comment]
Replace EK Paradox dll with this version

http://emptykeys.com/LinkClick.aspx?fileticket=v--5XFLwMxY%3d&portalid=0

**Comment by h-sao** [comment]
Awesome! Thank you for the quick response :)
It works!

**Comment by xen2** [comment]
We have realized that strong signing + versioning of assemblies is not a good idea for plugin providers as they would need to release plugin each Paradox version (or force users to use binding redirect).

We will make sure to change that, to make plugin development and use a smoother experience.

**Comment by EmptyKeys** [comment]
Cool xen2 :) looking forward for new versions
